### PR TITLE
is .val() the prob? and even if it is, can I fix it?

### PR DESCRIPTION
**Pull request by JoshMB**
My thinking is that .val() changes the current value. So I’m trying to
grab the current value, append, and then put it all back.

(Clearly, I got some work to do on my js and jQuery.)

### CODE REVIEW

**Comment by JoshMB** [comment]
That didn't work.

**Comment by rneiss** [comment]
you're selecting the wrong value -- you want something closer to:

 if( !tinyMCE.activeEditor || tinyMCE.activeEditor.isHidden()) {
  var currentText = jQuery('textarea#content').val();
jQuery('textarea#content').val(currentText+" "+shortcode);
 } else {
tinyMCE.execCommand('mceInsertContent', false, shortcode);
 }

On Wed, Aug 24, 2016 at 2:48 PM, Josh Mason-Barkin <notifications@github.com

**Comment by rneiss** [comment]
val() both reads or sets the current value (usually of a form element) in this case the `textarea` that contains the html code. 

Not sure where you're `#edit` selector is coming from. As far as I can tell it doesn't exist on the page.

Closing this regardless as it's fixed in the latest commit.

**Comment by JoshMB** [comment]
(I meant to add an `#edit` selector to one of the divs up top. <sigh>)

**Pull request closed without merging**
